### ISSUE TITLE
Solve crashes when standard deviation is zero

### ISSUE THREAD

**Issue by adamjermyn** [JohannesBuchner/PyMultiNest#97] opened 2018-01-23 14:10 UTC
When the computed standard deviation at the end of a run is zero, the solve function crashes. This occurs when solve calls the analyse function. The callback is below:

`  File "infer_multinest.py", line 120, in run
    result = solve(LogLikelihood=prob, Prior=pri, n_dims = ndim, importance_nested_sampling=True,resume=False,outputfiles_basename=prefix,verbose=True, n_live_points=100, max_iter=1000, write_output=False)
  File "/home/asj42/.local/lib/python3.5/site-packages/pymultinest/solve.py", line 73, in solve
    stats = analyzer.get_stats()
  File "/home/asj42/.local/lib/python3.5/site-packages/pymultinest/analyse.py", line 100, in get_stats
    for i in range(2, posterior.shape[1]):
IndexError: tuple index out of range
`
This error only comes up when the computed standard deviation is zero, which seems to only happen when the run is terminated pre-convergence by setting a non-zero max_iter. I think it makes sense that it vanishes in this case, because the likelihood gap between successive samples is large, but it would be better if the analyse function could detect this rather than crashing.

**Comment by JohannesBuchner** [comment] 2019-02-27 20:31
Just to clarify, the issue is not that the std is zero, but that there is only one single posterior point in the output files. This makes numpy.loadtxt believe it is supposed to read a 1d array instead of a 2d array.

**Comment by JohannesBuchner** [comment] 2019-02-28 16:07
I think this is fixed in the latest commit. If not, please reopen the issue.

**Closed by JohannesBuchner** 2019-02-28 16:07 UTC
