### ISSUE TITLE
Unable to make MultiNest

### ISSUE THREAD

**Issue by joeastro5** [JohannesBuchner/PyMultiNest#166] opened 2020-07-20 18:54 UTC
Hello. Following the tutorial http://johannesbuchner.github.io/PyMultiNest/install.html#install-on-mac, I am trying to make MultiNest, which gives me

`[joe@Josephs-MBP build % make    `
`[ 60%] Built target multinest_static`
`[ 60%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/nested.F90.o`
`/Users/joe/MultiNest/src/nested.F90:1072:16:`

 `1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)`
`      |                        2`
 `1072 |  call MPI_BCAST(ic_npt(1:ic_n),ic_n,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)`
  `    |                                  1`
`Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)`
`/Users/joe/MultiNest/src/nested.F90:1079:21:`

` 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)`
 `     |                2     `
`......`
 `1079 |       call MPI_BCAST(ic_done(0:ic_n),ic_n+1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)`
 `     |                     1`
`Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).`

And many more similar errors. I am on MacOS Catalina. Any help would be appreciated, I am not sure what these errors mean.

**Comment by JohannesBuchner** [comment] 2020-07-20 19:05
What compiler is being used? Try to delete everything in build and run cmake again, if you changed your system (e.g., compiler, libraries) in the meantime.

**Comment by joeastro5** [comment] 2020-07-20 19:48
I am using ifort. After doing your suggestion, I get a a different error. First I get 190 warnings like

`/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing`
`      a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]`
`        unsigned char   *_base;`
`                        ^`
`/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: note: insert '_Nullable' if`
 `     the pointer may be null`
`        unsigned char   *_base;`
  `                      ^`
  `                        _Nullable `
`/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: note: insert '_Nonnull' if`
 `     the pointer should never be null`
 `       unsigned char   *_base;`
 `                       ^`
`                          _Nonnull `
Followed by error
`[ 61%] Linking C executable ../../../bin/eggboxC`
`Undefined symbols for architecture x86_64:`
`  "___nested_MOD_nestrun", referenced from:`
 `     _run in eggbox.c.o`
`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by JohannesBuchner** [comment] 2020-07-20 20:02
try 'make clean' as well

**Comment by JohannesBuchner** [comment] 2020-07-20 20:03
The eggbox.c.o may be outdated

**Comment by joeastro5** [comment] 2020-07-20 20:59
Make clean runs fine. Make itself still gives the same error. Full output of make clean is

`joe@Josephs-MBP build % make clean`
`/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 clean
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/CMakeFiles/multinest_static.dir/build.make src/CMakeFiles/multinest_static.dir/clean
cd /Users/joe/MultiNest/build/src && /opt/local/bin/cmake -P CMakeFiles/multinest_static.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/CMakeFiles/multinest_mpi_shared.dir/build.make src/CMakeFiles/multinest_mpi_shared.dir/clean
cd /Users/joe/MultiNest/build/src && /opt/local/bin/cmake -P CMakeFiles/multinest_mpi_shared.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/CMakeFiles/multinest_mpi_static.dir/build.make src/CMakeFiles/multinest_mpi_static.dir/clean
cd /Users/joe/MultiNest/build/src && /opt/local/bin/cmake -P CMakeFiles/multinest_mpi_static.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/CMakeFiles/multinest_shared.dir/build.make src/CMakeFiles/multinest_shared.dir/clean
cd /Users/joe/MultiNest/build/src && /opt/local/bin/cmake -P CMakeFiles/multinest_shared.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_ackley/CMakeFiles/ackley.dir/build.make src/example_ackley/CMakeFiles/ackley.dir/clean
cd /Users/joe/MultiNest/build/src/example_ackley && /opt/local/bin/cmake -P CMakeFiles/ackley.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_eggbox_C/CMakeFiles/eggboxC.dir/build.make src/example_eggbox_C/CMakeFiles/eggboxC.dir/clean
cd /Users/joe/MultiNest/build/src/example_eggbox_C && /opt/local/bin/cmake -P CMakeFiles/eggboxC.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_eggbox_C++/CMakeFiles/eggboxC++.dir/build.make src/example_eggbox_C++/CMakeFiles/eggboxC++.dir/clean
cd /Users/joe/MultiNest/build/src/example_eggbox_C++ && /opt/local/bin/cmake -P CMakeFiles/eggboxC++.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_gaussian/CMakeFiles/gaussian.dir/build.make src/example_gaussian/CMakeFiles/gaussian.dir/clean
cd /Users/joe/MultiNest/build/src/example_gaussian && /opt/local/bin/cmake -P CMakeFiles/gaussian.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_gauss_shell/CMakeFiles/gauss_shell.dir/build.make src/example_gauss_shell/CMakeFiles/gauss_shell.dir/clean
cd /Users/joe/MultiNest/build/src/example_gauss_shell && /opt/local/bin/cmake -P CMakeFiles/gauss_shell.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_himmelblau/CMakeFiles/himmelblau.dir/build.make src/example_himmelblau/CMakeFiles/himmelblau.dir/clean
cd /Users/joe/MultiNest/build/src/example_himmelblau && /opt/local/bin/cmake -P CMakeFiles/himmelblau.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_obj_detect/CMakeFiles/obj_detect.dir/build.make src/example_obj_detect/CMakeFiles/obj_detect.dir/clean
cd /Users/joe/MultiNest/build/src/example_obj_detect && /opt/local/bin/cmake -P CMakeFiles/obj_detect.dir/cmake_clean.cmake
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f src/example_rosenbrock/CMakeFiles/rosenbrock.dir/build.make src/example_rosenbrock/CMakeFiles/rosenbrock.dir/clean
cd /Users/joe/MultiNest/build/src/example_rosenbrock && /opt/local/bin/cmake -P CMakeFiles/rosenbrock.dir/cmake_clean.cmake`

**Comment by JohannesBuchner** [comment] 2020-07-20 21:12
Can you try to compile with gcc?

**Comment by JohannesBuchner** [comment] 2020-07-20 21:16
Another user recommended: `On e.g. Mac OSX, make sure the correct compilers are used by calling cmake using -DCMAKE_C_COMPILER=/path/to/gcc -DCMAKE_CXX_COMPILER=/path/to/g++`
see https://github.com/JohannesBuchner/PyMultiNest/blob/master/doc/install.rst#2-building-the-libraries

Unfortunately, I don't have a Mac, so my debugging abilities are limited. We could tag some users from the other MacOS issues, maybe they can help.

**Comment by joeastro5** [comment] 2020-07-20 22:34
I tried `DCMAKE_C_COMPILER=/opt/local/bin/gcc` and  `DCMAKE_CXX_COMPILER=/opt/local/bin/g++` , and did `make clean` again in case, and I still get `clang: error: linker command failed with exit code 1 (use -v to see invocation)` when doing make. If it is possible to tag some of those users maybe that would help.

**Comment by joeastro5** [comment] 2020-07-21 06:32
I have also tried following the advice in https://solarianprogrammer.com/2019/10/12/compiling-gcc-macos/, compiling gcc10 in Catalina.
Any chance anyone has any ideas? Specifically with the make error `clang: error: linker command failed with exit code 1 (use -v to see invocation)`Thanks in advance! @Steelhead86 @hposborn @carolinestraatman @JVSeidel @matteobiagetti

**Comment by hposborn** [comment] 2020-07-21 14:41
I'm trying to remember how I fixed this. I thought it was just the DYLD paths, but maybe not. I did install gcc-9 and then made sure "gcc" was pointing at it, so you can try that (clearly, if you're getting a clang error, it's using the default gcc and not the brew-installed one).

Here's some select parts of my `.bashrc` (well, `.zshrc` actually) which may help you:
```
#Find where GCC is installed and alias "gcc" to that location:
alias gcc=/usr/local/Cellar/gcc/9.3.0_1/bin/gcc-9
alias g++=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export PATH=/usr/local/gcc-9.2/bin:$PATH

#I cant remember why, but the "install GCC on catalina" pages suggest the following list of flags which may be necessary:
export CFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
export CCFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -lstdc++"
export CXXFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
export CPPFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
export CC=/usr/local/Cellar/gcc/9.3.0_1/bin/gcc-9
export CXX=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export CXX11=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export CXX14=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export CXX17=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export CXX1X=/usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
export LDFLAGS=-L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9

#For compilers to find openssl@1.1 you may need to set:
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

#From MultiNest, mskr sure you have the MultiNest libraries in LD_LIBRARY_PATH and DYLD_LIBRARY_PATH, as well as the gcc libraries in DYLD_LIBRARY_PATH:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Users/hosborn/python/MultiNest/lib
export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/:/Users/hosborn/python/MultiNest/lib
```

**Comment by JohannesBuchner** [comment] 2020-07-21 15:29
The aliases are not used by programs (only the shell itself), but the other variables (CC,CXX,*FLAGS,*PATH) could do the trick.

**Comment by joeastro5** [comment] 2020-07-21 18:52
Thank you for the help @hposborn. After setting the flags, I don't get the old clang error, but instead get

`Undefined symbols for architecture x86_64:`
`  "___nested_MOD_nestrun", referenced from:`
 `     _run in eggbox.c.o`
`ld: symbol(s) not found for architecture x86_64`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [../bin/eggboxC] Error 1`
`make[1]: *** [src/example_eggbox_C/CMakeFiles/eggboxC.dir/all] Error 2`
`make: *** [all] Error 2`

**Comment by hposborn** [comment] 2020-07-21 19:38
`ld: symbol(s) not found for architecture x86_64` looks very familiar to me from my days of failing with this problem... if only I made better notes of how I fixed those. :/. Did you try re-installing fresh with those new flags?

I note that my initial `export LDFLAGS` line was being over-written later, so maybe it's necessary to have `export LDFLAGS="-L/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9 -L/usr/local/opt/openssl@1.1/lib"`

I also have the following lines in my .bashrc near the mess I made fixing Multinest, so these may help too:
`export PKG_LIBS=-L/usr/local/Cellar/gettext/0.18.3.2/lib
export PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
export PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/Cellar"
export cfitsio="/home/hosborn/python/cfitsio-3.47"`

**Comment by joeastro5** [comment] 2020-07-21 21:05
I did try re-installing, and it does not seem to work. Maybe a problem is that my gcc is in `/opt/local/bin/gcc`? (I'm new to a lot of this). I'll do some more searching online about the symbol not found error.

Not sure how important it is, but some of the other suggestions did not work:

`joe@Josephs-MBP build % export PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)`
`zsh: command not found: SHLIB_OPENMP_CXXFLAGS`
`zsh: bad assignment`
`joe@Josephs-MBP build % export PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)`
`zsh: command not found: SHLIB_OPENMP_CFLAGS`
`zsh: command not found: LAPACK_LIBS`
`zsh: command not found: BLAS_LIBS`
`zsh: command not found: FLIBS`
`zsh: bad assignment`

**Comment by rluquer** [comment] 2020-07-27 20:30
I have the exact same error than the one at the beginning of the thread...

**Comment by JohannesBuchner** [comment] 2020-07-27 20:38
You can't have spaces between variables and their values 

change
```
export PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
```
to
```
export PKG_CXXFLAGS=$(SHLIB_OPENMP_CXXFLAGS)
```

**Comment by JohannesBuchner** [comment] 2020-07-27 20:44
If all fails, you can try UltraNest instead.

**Comment by rluquer** [comment] 2020-07-28 01:34
This is the output of the cmake command

`MacBookPro-Rafa:build rluque$ cmake ..
-- The Fortran compiler identification is GNU 10.1.0
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/local/bin/gfortran - skipped
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Found BLAS: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Detected gfortran, adding -ffree-line-length-none compiler flag.
-- Found MPI_C: /usr/local/lib/libmpi.dylib (found version "3.0") 
-- Found MPI_CXX: /usr/local/lib/libmpi_cxx.dylib (found version "3.0") 
-- Found MPI_Fortran: /usr/local/lib/libmpi_usempif08.dylib (found version "3.0") 
-- Found MPI: TRUE (found version "3.0")  
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   multinest_mpi_shared
   multinest_shared

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/rluque/Documents/MultiNest/build`

**Comment by joeastro5** [comment] 2020-07-28 02:51
Thanks. Switching to export PKG_CXXFLAGS=$(SHLIB_OPENMP_CXXFLAGS) has not worked, so I think I will try UltraNest instead. (I got MultiNest working on Linux remotely, but I would like to have something on my Mac)

@rluquer, I notice cmake says you are using Clang. One of my problems went away went I instead had
`-- The C compiler identification is GNU 9.3.0`
Try some of hposborn's suggestions, export CFLAGS etc.

**Comment by mattpitkin** [comment] 2020-08-03 15:25
@joeastro5 another option is to use Anaconda/[Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html), and create a new environment and then install MultiNest from conda-forge, e.g., `conda install -c conda-forge multinest` (or just install PyMultiNest through conda, `conda install -c conda-forge pymultinest`, and it will install multinest too)

**Comment by tomasstolker** [comment] 2021-01-07 11:30
As mentioned by others already, the issue is probably related to the `gcc` version. I could circumvent the error by downgrading `gcc` from version 10 to 9:

https://github.com/farhanferoz/MultiNest/issues/7

It seems that there is a PR on the `MultiNest` page that fixes this issue:

https://github.com/farhanferoz/MultiNest/pull/8

So you could probably clone and checkout that branch since the PR hasn't been merged yet.

**Comment by JohannesBuchner** [comment] 2022-02-15 10:34
I am closing this because it is not a PyMultiNest bug.

**Closed by JohannesBuchner** 2022-02-15 10:34 UTC
