### ISSUE TITLE
Incorrect value in 2nd column of post_separate.dat file

### ISSUE THREAD

**Issue by ash2223** [JohannesBuchner/PyMultiNest#231] opened 2023-04-11 20:29 UTC
Hi Johannes,

I've successfully run MultiNest with MontePython using PyMultiNest, but when I try to analyze the run I get this error:

<img width="739" alt="Screen Shot 2023-04-11 at 1 25 15 PM" src="https://user-images.githubusercontent.com/61329093/231280159-579ace99-6647-4b4d-b5a2-562f28f33692.png">

From this error, I figured there were typos in the post-separate.dat file. Sure enough, every entry in the second column looks like this:

<img width="635" alt="Screen Shot 2023-04-11 at 1 27 03 PM" src="https://user-images.githubusercontent.com/61329093/231280519-f81ac067-a4f3-4b3c-9bf2-2f0e43ea7006.png">

I'm wondering if every entry in the second column should read, for instance, "-0.139058786410114508E-308" rather than "-0.139058786410114508-308"? I'm thinking there is some failure in either MontePython or MultiNest where the "E" is not getting printed. Am I correct in thinking this? Have you seen this issue before? Thanks so much!

-Adam

**Comment by JohannesBuchner** [comment] 2023-04-12 08:35
Duplicate of  #212

**Closed by JohannesBuchner** 2023-04-12 08:35 UTC
