### ISSUE TITLE
pymultinest_demo.py fails on linux with intel compiler

### ISSUE THREAD

**Issue by jcwright77** [JohannesBuchner/PyMultiNest#86] opened 2017-05-15 14:57 UTC
Running pymultinest fails on linux with intel compiler. demos in Multinest work. pymultinest_demo produces an Nan in the chains output and only does 400 likelihood evaluation vs 5644 on a know working older installation using gcc. I think I've tracked the issue down to the the 'cube' argument in the call to SafePrior. In the fortran code, this argument is a list of floating point values, but in python call, it is an empty list. I'm not a ctypes expert, but it seems something is wrong there.

**Comment by JohannesBuchner** [comment] 2017-05-15 15:20
Which Multinest version are you using? (from where? cmake or non-cmake?)

Does pymultinest_demo_old.py still work for you?

**Comment by jcwright77** [comment] 2017-05-15 15:30
Hi Johannes
we are using multinest 3.10  built with cmake

pymultinest_demo_old.py crashes when trying to open a plot window, but output looks bad anyway:

Acceptance Rate:                        1.000000
Replacements:                               1000
Total Samples:                              1000
Nested Sampling ln(Z):            **************
 ln(ev)=   243.000000000000      +/-                     NaN
 Total Likelihood Evaluations:         1000
 Sampling finished. Exiting MultiNest
  analysing data from chains/2-.txt

------------------------------ ANALYSIS ------------------------------
Global Evidence:
	2.430000000000001e+02 +- nan



This NaN occurs in other tests as well and seems to derive from the term 


IS_Z(2) = sqrt(exp(IS_Z(2)-2d0*IS_Z(1)) - 1d0/IS_counter(1))
in nested.F90 where IS_counter(1) is zero.
I think that is just a symptom of some deeper problem though.

Note that the demo programs in Multinest itself seem to work. 

-john

**Comment by JohannesBuchner** [comment] 2017-05-15 15:38
I think you get a NaN if the function returns the same value every time (the integration stops, because the function looks flat and the counter might also be zero). 

The problem is probably in pymultinest not passing things along correctly.

If you print a and b in SafePrior, do they have reasonable values? cube is a ctypes double array, you need [cube[i] for i in range(ndim)] to access the values.
Can you also print what SafeLogLikelihood returns in l = float(LogLikelihood(a))?

**Comment by JohannesBuchner** [comment] 2017-05-15 15:39
I don't have icc installed at the moment but will try later this week.

**Comment by jcwright77** [comment] 2017-05-15 15:42
> On May 15, 2017, at 11:38 AM, Johannes Buchner <notifications@github.com> wrote:
> 
> I think you get a NaN if the function returns the same value every time (the integration stops, because the function looks flat and the counter might also be zero).
> 
> The problem is probably in pymultinest not passing things along correctly.
> 
> If you print a and b in SafePrior, do they have reasonable values? cube is a ctypes double array, you need [cube[i] for i in range(ndim)] to access the values.

No, a is an empty list, b=243.0
in SafeLogLikelihood, l=243.0 and ‘a’ is an empty list.
This is how far I had gotten in the debugging when I posted this issue.
thanks

-john

**Comment by JohannesBuchner** [comment] 2017-05-15 16:02
Aha! that means ndim=0
The loglikelihood computes a empty product --> chi=1 and returns (2+1)**5=243.
This might be either a problem with over-eager garbage collector, or multinest does not pass the ndim argument correctly for some reason. At the start multinest says "dimensionality =  2"?

A solution could be to replace ndim with n_dims in SafePrior and SafeLikelihood.

**Comment by JohannesBuchner** [comment] 2017-05-15 16:10
If you get a chance, could you try with the latest commit which tries to prevent garbage collection.

**Comment by jcwright77** [comment] 2017-05-15 16:28
i'll check on ndim and latest revision in a few hours. thanks

-john

On May 15, 2017, at 12:10 PM, Johannes Buchner <notifications@github.com<mailto:notifications@github.com>> wrote:


If you get a chance, could you try with the latest commit which tries to prevent garbage collection.

**Comment by jcwright77** [comment] 2017-05-15 19:10
dimensionality is 2:
[jcwright@eofe7 Tests]$ python /home/software/psfc/local/lib/py27/pymultinest/pymultinest_demo.py
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 debug jcw loglike cube 1  0.720859110355377       0.607928574085236
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000


The debug output is the value of ‘cube’ when loglike is called in nested.F90,
this value becomes and empty list inside the python def of safeloglikelihood

This test is from pymultinest2.2.tar.gz retrieved from pip.

.

Retrieving pymultinest from git hub
git clone https://github.com/JohannesBuchner/PyMultiNest.git
This identifies as pymultinest 2.3

Running the pymultinest_demo.py produces the same result.
Note I print out the first argument in loglike in the fortran call and it is a reasonable list of floating point values.
In myloglike, defined in pymultinest_demo.py I print out the arguments of the call. Now it looks like the values of cube are there, but n and n are negative integers. There is a clue in the error output that these integer references are no longer valid:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/software/psfc/local/lib/py27/pymultinest/run.py", line 211, in loglike
    Prior(cube, ndim, nparams)
  File "./pymultinest_demo.py", line 19, in myprior
    print('jcw cube in myprior', cube,cube[0],cube[:],'xx',ndim,nparams,str(type(ndim)))
MemoryError

This error occurred when I tried to print the full range of values in  cube. (cube[:]), however cube[0:1] produces no memory reference error.
Printing ndim and nparams gives values:  -63352 -63348 and type ‘int'


If I hardwire nparams and ndim inside the def of myprior and myloglike in pymultinest_demo.py, everything runs fine and I even get the progressive output plots. The crash in pyplot in the analysis phase still occurs with the fix to ndim and nparams though.



Output is below of a run.


[jcwright@eofe7 Tests]$ python ./pymultinest_demo.py
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    2
 *****************************************************
 Starting MultiNest
 generating live points
 debug jcw loglike cube 1  0.544632017612457       0.775739371776581
 <debug output clipped>
…
debug jcw loglike cube 1  0.395274698734283       0.239353418350220
  0.731415808200836       3.261017799377441E-002  0.934186577796936
  0.244119107723236       0.160472035408020       0.727830052375793
  0.151004135608673       0.819092750549316       0.350605905056000
  0.321970701217651       0.642200648784637       0.966931641101837
  0.641258239746094       0.244245409965515       0.932430803775787
  0.162693202495575       0.765198528766632       0.930921018123627
 live points generated, starting sampling
Acceptance Rate:                        1.000000
Replacements:                               1000
Total Samples:                              1000
Nested Sampling ln(Z):            **************
 ln(ev)=   243.000000000000      +/-                     NaN
 Total Likelihood Evaluations:         1000
 Sampling finished. Exiting MultiNest
  analysing data from chains/2-.txt

------------------------------ ANALYSIS ------------------------------
Global Evidence:
	2.430000000000001e+02 +- nan
Traceback (most recent call last):
  File "./pymultinest_demo.py", line 59, in <module>
    plt.clf()
  File "/home/software/sloan/local/lib/py27/matplotlib/pyplot.py", line 673, in clf
    gcf().clf()
  File "/home/software/sloan/local/lib/py27/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/software/sloan/local/lib/py27/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/software/sloan/local/lib/py27/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/software/sloan/local/lib/py27/matplotlib/backends/backend_tkagg.py", line 98, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/cm/shared/engaging/python/2.7.12/lib/python2.7/lib-tk/Tkinter.py", line 3367, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/cm/shared/engaging/python/2.7.12/lib/python2.7/lib-tk/Tkinter.py", line 3321, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop


This is git hash : 4dd0602

thanks,
-john

**Comment by JohannesBuchner** [comment] 2017-05-15 19:37
I am not sure that last run is really from v2.3, because there should not be a line 59 in pymultinest_demo.py. If you ran pymultinest_demo_old.py here: Yes, you can ignore the plotting thing, if you run pymultinest_demo_minimal.py instead of pymultinest_demo_old.py it comes without the ProgressPlotter.

> This error occurred when I tried to print the full range of values in cube. (cube[:]), however cube[0:1] produces no memory reference error. Printing ndim and nparams gives values: -63352 -63348 and type ‘int'

Okay, then it is probably garbage collected away. Could you try the now-latest commit, b76c786, and see if the result is the same?

This is all 64 bit, including the multinest compilation and python executable?

**Comment by jcwright77** [comment] 2017-05-15 20:13
My mistake,
I was still running a different pymultitest_demo.py that still included the plotting.

The one including with pymultinest 2.3 is different. It  no longer has the plotting commands and also does not have ndim and nparams as arguments to myprior and myloglike.
It doesn’t crash but the answer doesn’t seem right:

[jcwright@eofe7 PyMultiNest]$ python ./pymultinest_demo.py
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   243.000000000000      +/-  3.381217623635014E-007
 Total Likelihood Evaluations:          400
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 243.0 +- 0.0

parameter values:
              x : 0.493 +- 0.279
              y : 0.485 +- 0.292



.

Everything is 64 bit I believe. Multinest library says: ELF 64-bit LSB shared object, x86-64
and python says architecture is 64 bit.


Output of b76c786 is about the same:
MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   243.000000000000      +/-  3.381217623635014E-007
 Total Likelihood Evaluations:          400
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 243.0 +- 0.0

parameter values:
              x : 0.507 +- 0.284
              y : 0.509 +- 0.283


.
Do you have reference output for pymultinest_demo.py ?

pymultinest_demo_minimal.py produces about the same output as well.

thanks,
-john

**Comment by JohannesBuchner** [comment] 2017-05-15 20:18
You can add verbose=True to the solve() call, if you want to see the usual Multinest output.

For me the output is:
```
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.8
 Copyright Farhan Feroz & Mike Hobson
 Release Oct 2014

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   235.96489255430433      +/-  0.12273843306709455     
 Total Likelihood Evaluations:         5320
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 236.0 +- 0.1

parameter values:
              x : 15.215 +- 9.075
              y : 15.618 +- 8.876
```

The run output you posted is still not correct, with ndim is still 0, because loglikelihood still returns (2+1)**5, always. Strange.

**Comment by jcwright77** [comment] 2017-05-15 20:40
With this version cube is being passed back as an empty list again to myprior and mylikelihood.
verbose = True does not add much helpful to the output.

Running pymultinest_demo_old.py produces:
 live points generated, starting sampling
Acceptance Rate:                        1.000000
Replacements:                               1000
Total Samples:                              1000
Nested Sampling ln(Z):            **************
 ln(ev)=   243.000000000000      +/-                     NaN
 Total Likelihood Evaluations:         1000
 Sampling finished. Exiting MultiNest
  analysing data from chains/2-.txt

Running my instrumented version of pymultinest_demo_old.py produces:
Acceptance Rate:                        0.370754
Replacements:                               9310
Total Samples:                             25111
Nested Sampling ln(Z):                235.458894
 ln(ev)=   235.805140611944      +/-  7.855027946899508E-002
 Total Likelihood Evaluations:        25111
 Sampling finished. Exiting MultiNest
  analysing data from chains/2-.txt

------------------------------ ANALYSIS ------------------------------
Global Evidence:
	2.358051406119443e+02 +- 7.855027946899508e-02
then  a crash in Tkinter.py
This output though , seems more in line with yours. The only difference is print statements in the myprior and mylikelihood functions.
Add print statements to the newer pymulinest_demo.py only shows an empty list.
-john

**Comment by JohannesBuchner** [comment] 2017-05-15 21:06
The second output is correct -- seems like you got pymultinest_demo_old.py working. But what is different compared to your first output? Only whether you run pymultinest_demo.py instead of pymultinest_demo_old.py, or with your modifications in pymultinest/solve.py?

**Comment by jcwright77** [comment] 2017-05-15 21:55
The only difference appears to be the print statement I added below: 

def myprior(cube, ndim, nparams):
        print ('jcw cube in myprior',cube[0:1],str(type(cube)),ndim,nparams,str(type(ndim)),str(type(nparams)))
        ndim=2
        nparams=2
        for i in range(ndim):
                cube[i] = cube[i] * 10 * math.pi

It seems the presence of the extra arguments is enough to keep cube from being garbage collected. Though ndim and nparams are returned with negative integer values (maybe pointers?).

If I run pymultinest_demo_minimal.py, and add these lines it also works.
-john

**Comment by JohannesBuchner** [comment] 2017-05-16 00:00
I think only the ndim=2 is making the difference here. That means we haven't addressed the problem at all.

**Comment by jcwright77** [comment] 2017-05-16 02:57
I don’t think we’ve solve the problem but there definitely seems to be a connection between the presence of more arguments in definition of myprior and myloglike and whether ‘cube’ persists.

to be explicit:
in the git hub pymultinest distribution, pymultinest_demo.py has only ‘cube’ as an argument to those two functions. In the multicast library, the value passed to the cube argument is defined and is reasonable, in the call to myprior and myloglike it shows up as an empty list.

In pymultinest_demo_old.py, the two functions have three arguments : cube, ndim and nparams. This is the only substantive difference between the two demos. Yet, this demo always has the value of cube presents for a two element length of cube. And in this case, ndim and nparams are nonsensical or perhaps not defined correctly in ctypes. If ndim and nparams are set explicitly to 2 then the whole demo works.

So the question is, what makes the difference in these two demos that causes cube to be an empty list in one case (trying to access cube[0] or cube[1] throws an access error) and in the other case the values are present. This suggests to me there is something going on with argument persistence and perhaps garbage collection. Though I tried to turn gc off at the begging of the demo and that didn’t have an effect. Maybe it has to be put elsewhere?

-john

**Comment by JohannesBuchner** [comment] 2017-05-16 03:39
> in the git hub pymultinest distribution, pymultinest_demo.py has only ‘cube’ as an argument to those two functions. In the multicast library, the value passed to the cube argument is defined and is reasonable, in the call to myprior and myloglike it shows up as an empty list.

If I understood your outputs and investigations correctly, it is only an empty list because ndim is <= 0. You were always able to access cube[0] and cube[1].

There are more differences between the demos: one calls pymulltinest.solve.solve(), the other pymultinest.run(). The latter is closer to Multinest, the former additionally does a wrapper (SafePrior and SafeLogLikelihood) which convert the ctypes double array `cube` to a numpy array, by looping over the ndim elements. If ndim<=0, this produces an empty list.

I suspect icc and gcc have different conventions for the Fortran-C module, and icc might actually pass a pointer while gcc passes the value. A work-around is in a6430f2, which should make the pymultinest_demo.py work (but not pymultinest_demo_old.py).

**Comment by jcwright77** [comment] 2017-05-16 12:12
> On May 15, 2017, at 11:39 PM, Johannes Buchner <notifications@github.com> wrote:
> 
> in the git hub pymultinest distribution, pymultinest_demo.py has only ‘cube’ as an argument to those two functions. In the multicast library, the value passed to the cube argument is defined and is reasonable, in the call to myprior and myloglike it shows up as an empty list.
> 
> If I understood your outputs and investigations correctly, it is only an empty list because ndim is <= 0. You were always able to access cube[0] and cube[1].
> 
Not quite. In pymultinest_demo_old.py, cube is never an empty list but ndim is not set properly. In pymultinest_demo.py, ndim is not present in log likelihood and cube is always an empty list.

> There are more differences between the demos: one calls pymulltinest.solve.solve(), the other pymultinest.run(). The latter is closer to Multinest, the former additionally does a wrapper (SafePrior and SafeLogLikelihood) which convert the ctypes double array cube to a numpy array, by looping over the ndim elements. If ndim<=0, this produces an empty list.
> 
> I suspect icc and gcc have different conventions for the Fortran-C module, and icc might actually pass a pointer while gcc passes the value. A work-around is in a6430f2 <https://github.com/JohannesBuchner/PyMultiNest/commit/a6430f2bb41046705c3873a6e9718a6a93ce05e6>, which should make the pymultinest_demo.py work (but not pymultinest_demo_old.py).
> 
> 

I agree about the pointers. I was wondering in the ctypes type definitions whether changing int to pointer(int) would help. Generally, fortran never passes by value, always by pointer within the language itself. However, I’m not sure what is done in recent fortran c-interface language capabilities. I’ll try your latest change and let you know.

When extra time somehow appears, I’ll make a small test to really see the differences in gfortran vs ifort regarding fortran - c interoperability.

thanks,
-john

**Comment by jcwright77** [comment] 2017-05-16 12:12
> On May 15, 2017, at 11:39 PM, Johannes Buchner <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> in the git hub pymultinest distribution, pymultinest_demo.py has only ‘cube’ as an argument to those two functions. In the multicast library, the value passed to the cube argument is defined and is reasonable, in the call to myprior and myloglike it shows up as an empty list.
> 
> If I understood your outputs and investigations correctly, it is only an empty list because ndim is <= 0. You were always able to access cube[0] and cube[1].
> 
Not quite. In pymultinest_demo_old.py, cube is never an empty list but ndim is not set properly. In pymultinest_demo.py, ndim is not present in log likelihood and cube is always an empty list.

> There are more differences between the demos: one calls pymulltinest.solve.solve(), the other pymultinest.run(). The latter is closer to Multinest, the former additionally does a wrapper (SafePrior and SafeLogLikelihood) which convert the ctypes double array cube to a numpy array, by looping over the ndim elements. If ndim<=0, this produces an empty list.
> 
> I suspect icc and gcc have different conventions for the Fortran-C module, and icc might actually pass a pointer while gcc passes the value. A work-around is in a6430f2 <https://github.com/JohannesBuchner/PyMultiNest/commit/a6430f2bb41046705c3873a6e9718a6a93ce05e6>, which should make the pymultinest_demo.py work (but not pymultinest_demo_old.py).
> 
> 

I agree about the pointers. I was wondering in the ctypes type definitions whether changing int to pointer(int) would help. Generally, fortran never passes by value, always by pointer within the language itself. However, I’m not sure what is done in recent fortran c-interface language capabilities. I’ll try your latest change and let you know.

When extra time somehow appears, I’ll make a small test to really see the differences in gfortran vs ifort regarding fortran - c interoperability.

thanks,
-john

**Comment by jcwright77** [comment] 2017-05-22 18:29
I did run the test with a6430f2 and it appears to work.
So pymultinest_demo.py now works but pymultinest_demo_old.py still does not work as you said.

Thanks so much for your help so far. If we could get pymultinest.run working in addition to pymultinest.solve, I believe that would allow us to move ahead in our analysis here using pymultinest.

-john


Output:
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    2
 *****************************************************
 Starting MultiNest
 generating live points
 live points generated, starting sampling
Acceptance Rate:                        1.000000
Replacements:                               1000
Total Samples:                              1000
Nested Sampling ln(Z):            **************
 ln(ev)=   243.000000000000      +/-                     NaN
 Total Likelihood Evaluations:         1000
 Sampling finished. Exiting MultiNest
  analysing data from chains/2-.txt

------------------------------ ANALYSIS ------------------------------
Global Evidence:
	2.430000000000001e+02 +- nan
Traceback (most recent call last):
  File "/home/software/psfc/src/PyMultiNest/pymultinest_demo_old.py", line 72, in <module>
    p.plot_marginal(i, with_ellipses = True, with_points = False, grid_points=50)
  File "/home/software/psfc/src/PyMultiNest/pymultinest/plot.py", line 58, in plot_conditional
    min1 = min([mode['mean'][dim1] - 3*mode['sigma'][dim1] for mode in modes])
ValueError: min() arg is an empty sequence
[jcwright@eofe7 Tests]$ python  /home/software/psfc/src/PyMultiNest/pymultinest_demo.py
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   236.052208787708      +/-  0.122009930572547
 Total Likelihood Evaluations:         5612
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 236.1 +- 0.1

parameter values:
              x : 15.298 +- 8.995
              y : 15.761 +- 9.087

**Comment by JohannesBuchner** [comment] 2017-05-22 18:41
The new pymultinest.solve API should be more convenient to use than the pymultinest.run. Any reason why you can not change your code to that API?

**Comment by jcwright77** [comment] 2017-05-22 19:24
I will look and see. We have inherited a large python workflow for experimental data analysis. I’ll have to investigate the exact nature of the pymultinest calls.
thanks, I’ll leet you know what I find.
-john

**Comment by JohannesBuchner** [comment] 2017-05-22 20:27
The quick-fix solution for legacy code would be to use in the likelihood and prior solutions the global  n_params instead of the ndim available inside.

**Comment by JohannesBuchner** [comment] 2017-11-27 14:53
Hi @jcwright77, did you get it to work? Any recommendations for pymultinest users with icc?

**Comment by JohannesBuchner** [comment] 2019-02-27 19:48
Thanks @jcwright77 for looking into this. Closing for now.

**Closed by JohannesBuchner** 2019-02-27 19:48 UTC
